name: Android NDK + Java Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest

    env:
      # Ajuste os paths conforme o seu SDK / NDK version
      ANDROID_SDK_ROOT: ${{ runner.tool_cache }}/android-sdk
      NDK_VERSION: "25.2.9519653"  # Exemplo: NDK 25

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 9477386
        ndk-version: ${{ env.NDK_VERSION }}

    - name: Grant execute permissions to gradlew
      run: chmod +x ./gradlew

    - name: Build APK (Debug)
      run: ./gradlew assembleDebug
